# Generated by Django 3.1.1 on 2020-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200927_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Waiting_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدة الانتظار'),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=1, max_length=50, verbose_name='المحافظه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_detail',
            field=models.CharField(default=1, max_length=50, verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور؟'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(default=1, max_length=50, verbose_name='الهاتف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='specialist_doctor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='متخصص فى'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subtitle',
            field=models.CharField(default=1, max_length=50, verbose_name='الاسم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد ساعات العمل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='من انا'),
        ),
    ]
