# Generated by Django 3.1.1 on 2020-10-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_join_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=50, verbose_name='النوع'),
            preserve_default=False,
        ),
    ]
