# Generated by Django 3.1.1 on 2020-10-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_type_of_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('أسنان', 'أسنان'), ('أنف وأذن وحنجرة', 'أنف وأذن وحنجرة'), ('مخ واعصاب', 'مخ واعصاب'), ('أطفال حديثى الولادة', 'أطفال حديثى الولادة'), ('نساء وتوليد', 'نساء وتوليد'), ('جراحة اورام', 'جراحة اورام'), ('جلدية', 'جلدية'), ('أورام', 'أورام'), ('باطنة', 'باطنة'), ('تخسيس وتغذية', 'تخسيس وتغذية'), ('جراحة سمنة ومناظير', 'جراحة سمنة ومناظير'), ('قلب وأوعية دموية', 'قلب وأوعية دموية'), ('أمراض دم', 'أمراض دم'), ('نفسي', 'نفسي'), ('عظام', 'عظام'), ('جراحة تجميل', 'جراحة تجميل'), ('جراحة اطفال', 'جراحة اطفال')], max_length=50, null=True, verbose_name='دكتور؟'),
        ),
    ]
